### ISSUE TITLE
NLU and its training data?

### ISSUE THREAD

**Issue by ksurya** [RasaHQ/conversational-ai-workshop-18#14]
1. What sentences does the paper considers as Chitchat?
2. Does the example here https://github.com/RasaHQ/rasa_core/tree/master/examples/restaurantbot includes all the bAbI data?

**Comment by akelad** [comment]
Hi @ksurya apologies for not answering this sooner.
The paper considers chitchat as any sort of chitchat, so e.g. "what's the weather", "what time is it" etc. The idea was that there is a separate module that retrieves the correct chitchat responses. 
Yes, that example is the bAbI data converted into our format.

We didn't include NLU data in this repo for now because it wasn't really the focus of our paper
